### PR TITLE
Create azure-pipeline.yml

### PR DESCRIPTION
**Pull request by ivishalsinghal**

### CODE REVIEW

**Comment by ivishalsinghal** [comment]
ok

**Review by ivishalsinghal — COMMENTED** [review]
OK

**Comment by LorenzBuehmann** [comment]
Hi,
thanks for the PR but can you explain the purpose of this PR please?
as far as I can see, it just forces a `mvn package` execution on the master branch, but not sure what else happens here.

Moreover, this template project here was more supposed to be some kind of Maven stub sketching how to use SANSA artifacts in a Maven project.

**Comment by LorenzBuehmann** [comment]
We don't think it fits into this layer and we're still not sure what the purpose of this YAML file is.

If the TO responds we can discuss again and maybe forward to a different layer or just refer to it into Github Wiki entry or the like.

**Pull request closed without merging**
